### ISSUE TITLE
Why net5.0

### ISSUE THREAD

**Issue by YorkWong1995** [Touseefelahi/GigeVision#74]
hi,  recently i wanna use QT to call gigevision's function, so i use a CLR program wrapped C# dll.
however, VS2019 CLR dll project (face to .netframework) do not support .net5.0 because 5.0 is not LTS version
And CLR dll project(face to .net core) can't be used by QT 
So i am wondering why use a not LTS version and can i use .net 4.5+ to run this project?

**Comment by Touseefelahi** [comment]
There is a branch that will work for net4.8. Check if it works for you. Btw there would be some changes to make it work for older version. Kindly, update me with the result.Sent from my iPhoneOn 16 Sep 2022, at 2:21 PM, YorkWong1995 ***@***.***> wrote:﻿
hi,  recently i wanna use QT to call gigevision's function, so i use a CLR program wrapped C# dll.
however, VS2019 CLR dll project (face to .netframework) do not support .net5.0 because 5.0 is not LTS version
And CLR dll project(face to .net core) can't be used by QT
So i am wondering why use a not LTS version and can i use .net 4.5+ to run this project?

**Comment by Touseefelahi** [comment]
https://github.com/Touseefelahi/GigeVision/tree/4.8FrameworkCompatible

**Comment by YorkWong1995** [comment]
I used the 4.8framework branch and it works for me, but there is a little problem
When it displays at ImageControl. It displays three reduced images above the form.
I am trying to find reasons now
![abnormal_image](https://user-images.githubusercontent.com/54474676/192451100-00455931-64ed-462d-b3a0-323d9012849e.JPG)

here is the custom control in GigeVisonLibray.Test.Wpf
**<local:LightImage2 x:Name="lightControl" Grid.Row="1"/>**

**Comment by Touseefelahi** [comment]
@YorkWong1995 it's is because of the display control, try changing the property IsColored to true and false and check the result.

**Comment by YorkWong1995** [comment]
OK.  it solved!  thanks so much
