### ISSUE TITLE
Unable to stream with SVS camera

### ISSUE THREAD

**Issue by ericlim20** [Touseefelahi/GigeVision#88]
Hi,

There is an exception when retrieving the Width value from the camera. But the issue can be resolved after adding the _pNode.Name.EndsWith("IntReg") && pNode.Attributes["Name"].Value.EndsWith("Ctrl"))_ when getting the register.

![image](https://user-images.githubusercontent.com/70361545/210024694-01ec723f-8fb4-4688-afe4-4ec601671193.png)

However, I still encounter another issue when receiving the packet from the camera as below:

![image](https://user-images.githubusercontent.com/70361545/210024899-b308e390-5d00-4a44-bf1d-b6cbff37ce2d.png)

What I have to do in order to stream with SVS camera?

**Comment by Touseefelahi** [comment]
Enable jumbo packet if the packet size is more than 1500 bytes Sent from my iPhoneOn 30 Dec 2022, at 4:08 AM, ericlim20 ***@***.***> wrote:﻿
Hi,
There is an exception when retrieving the Width value from the camera. But the issue can be resolved after adding the pNode.Name.EndsWith("IntReg") && pNode.Attributes["Name"].Value.EndsWith("Ctrl")) when getting the register.

However, I still encounter another issue when receiving the packet from the camera as below:

What I have to do in order to stream with SVS camera?

**Comment by ericlim20** [comment]
It is working now. Perfect. Thanks a lot. But may I know why need to enable jumbo packet and what is 9KB MTU means?

![image](https://user-images.githubusercontent.com/70361545/210055933-86ed63db-fdaf-4e42-b23a-90156d19f740.png)

**Comment by Touseefelahi** [comment]
MTU is the maximum transmit unit, the maximum no. of bytes that can be transmitted in a single ethernet packet. 
So by default, the library sets the Packet Size equal to one row (+ header ) per packet, if this size is less than the default MTU size of 1500 then it will work fine.

In my experience, if we set the packet size high we get better performance.
